language: java
jdk:
- oraclejdk8
env:
  global:
    - secure: "HWCT+HDp4pcFfcFd03wkC16Qdu1RZu8nVcdeuH4b+jUQ3DcIYPaLtgyfVmyb6F0fprH6zcPAU/bbg6YCX5j9Dbve+tpFR5gijy2jCFLk3Hn6EnITKvpqUZ3IJTGIjmIT4+th9L1PE7JPbYXfIeJMAIZmntGmEOHHIq97u425TRfhtNag0K8V14xay83zSBx4dy21aIObewGoWYmQeIWVeroSBV+p2OHNHJuTxuMHxFtE4TgH85P4fD2wyxKT2CfHHNOosrrdSfs4DikUZCJhAZE67yFdGyRoD98e9dMiMkdqhNyTT49DtMSB4j4JOIU3s0GGixrgY4gHAQFjh/dfylVe5+x4qI0YhTpKpvErmCp9RQesfryfVNj/OGEsl23MPcrF+yEZW5TPN7POtDWneKYC0gQcjNo/9P0+Z6bdJFRHPKUzu012ua723yaR7jWjHVsn+oacmK8GwIyKRUBV5QhXA2NWIYocoBXNMQI5njKdZe2hyTVir2cMymD+oIy/Ev5jb3EsO/OQ6fNwwY2oqlilEWL7PzRtNzZYHZalU/sRwVvBXCvEEBXO7dWhoOE1ZZpKDddw2Bv8j+6yVKKH1vs9n0JQxRaufEjduTS9uDc4fG1soolY3hZE+q2aCegQmsBGygFl0mK1nH82VsyscNJ0PCI05nHkFtpJziL2ngI="
    - # ^^ GPG_KEY_NAME
    - secure: "tG10/NXnDcwEFn+eQhOQgB4DQWc2G+aDEeXGpxKvJkbVtrpK74kyfsZy2B2LhmSGf4uCgsRgpoW62/uPLFbyY2Cgy405lIVthzo8xdiz6ujgLzPbVMtFlG2TD9Zlcj4g66JsdtRTQw1w8bMIyE6oYkyAVb0I7wNN0h3CsvcFdrW4rl7/JmQNJCQMeSHJ1J+fa8YU2mM5Ak9nJJSuMhef6otagm0x+Pn54KyG1YHXz2RBKEuZqJNbwVQ7Z9BseR44B/GzvxD9OHPyxr7DE3tVjSB0vjzQA2jjSTxf1zaJd37nADXO5P1NK6r9zktGeauQI8oqOIu3URxGfWC2tOnI5SOvaDggXG/1Rxk/L6y1YOiHY+mK0pfsEP2Bs2fWGsCWDLQHPQg3SI586NxP80RM0Bm+iiPjeRxLG64WMAWrqrVIrnE798v+L8OZKhQ9W5tjdxqv+mtUOpPZFJOOo+7cL3RBzpzlmpUXRS5kWVz7PmBcOpdjioOQXgS/WUGCYH7mq3LAWNTYmWCfo48wuhOP9AXKB10IlWLbIPCkbiHyGW8mQU5JAi9G+uh2Rg0wf9QqdgE9nFQ/GfT2cRija6Sqhbs2E0qNh6qSpxsoM5VltEBI8R1sQDt6x0+194JWkB8iP5ebv1dsjY49mp9rgm1AbgUPYRs727SUShdBw8xOulA="
    - # ^^ GPG_PASSPHRASE

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./travis/before_deploy.sh
  - ./travis/deploy.sh
