language: java
jdk:
- oraclejdk8
env:
  global:
    - secure: "gkHjtbgXwu/7KYy+mxKBQYtl1v9qywHOt3DzXFLLlEAkuL6S9KgURet5qZ+Q7TpqjsRI/Qnc2mh/UMUAbTPoljWV5N3hI2SBvyvjgKEGamQpKgqXndG7M2ZdVwgHXL9p3k+ZRKMNCQGRjU0fkGUtvRPAYNoBNwjZ/UQChwtW2JnTTAQjbKnS37I5Q+sOjl9BfatSJqyMSySuZZE7UKJ82AtMvvYx6Rx4+x2dXhcmxTQjTaGM8OPkrV239/LqqWGTcvnvFZLwBpm7eIiM9FqzAliiOZQwwv0yMyQJQm8pad2K04vNeURDpbqj3EeWz/ciebrhgLhDqmCiMrBWYikrEczuElCnD2/xURmkUD0MRSUir6WHNk3U4Cb+jX/lLKKKY7BWHIcAXcQsE9M8lulURaz7vntHQQpbuSJSK17e3uC3WQZ4v1VXMo9gW69/ebwMpsd6lnXXFiTuWNnojOv+++zppOUcIXbez4j6ZTCt5YV7kE5XCxoZRyAOc4JUq+kBTaEXUvmd5BLfrz6/2YDmVe5NoO6n3ftGXnFz0qlpvxCvc2+TADIv1VMVGIAeZuptZClNdkDwCw7xbTIVrbhNBywqconjN5WiSY2Tqm0yTB4s8aJsIoNE3uOVywxcpdia6f0q0rJptMMeIkxJcl4/LiHgUCC8vPqhQfSKf1Vf5M0="
    - # ^^ GPG_KEY_NAME
    - secure: "0e6oyG6XRt42hj95bVfcy5QfLdT+pS6rMQ2hGit6mzcoLrxwm+UDhcKKrXMOV2FBf794u+eu2xa4W+1yIx6hUXAqNJTQkXsu0hRwjYICwrB8GXxkleU+Ws/1ufptmQOkQaAfczMG2K550ZQtYQXtOlL/lQ2ImDyhrU1N4HSKXqkAi3P/eJaac7is6N5lo9UdDAq/6MVxiN21PsUilTNyf3AK+fZvlSimjZU7rfnrVEIH50vuqo0cfCkRIClQ/7m9RJcMigY0bQm0OS3f8+1ce+/55SShauCYHExpg0yQyezRK95p3LWRz29ZQQRS5g+JYuyfRuMi2KIXN3krxBPRVDoBkXSIgOXaBFrvDTWZQon2fxxTO6QyDlJBpOoa37HZkMIqpMB5jD7edPO0QER+T+AxuclUudAnoZGljzeaXIUv9D4LvJQR1R0rS+ofWJvKo2adsQO6BF8VnJ7EiPs+Ai1CopA8mbvmiTyBQno/DWBBsLD4ns1Ou7duGWFMvWLuXIuzyDEdcZT8tnBJiOpLaUUIKMuX6Gtbcxe0ExAzxpj5HfetyfqLhZwTPBIjt1dxs5t2QQdo59eQ3PNJIDa+RXAr7iJBsiRq4YmnPnm3QU95ueFhP1KdWeMHfGZNNbfrTXZrbyBt23uqnXLxJoqGkuAO9dqvSbZHea0GmB1eHl4="
    - # ^^ GPG_PASSPHRASE
    - secure: "vAPgB2gGPXvxRLuV5HcrxlUQXAE5jIotWSNZdMoLFKHGbDRW//sGDXm23HQ/L0JcbaH6XHc5YrGZHY0pwohY3CRVqZNaVnKDEZ8f9e5OKFfKMJ0Le+cRjCOps76jvWzhjY0XECHPc1B+8hQW07IvNEcvdYHCp/AGPror5EHhIt/L/vOhKmumG3PFuXjfBl6jQMrOcnCcdIxZrcKBxbZT0E8etS37tkEoADzNS5poXfljpCsqDRZaPp/U2Qb+ZYP84ifbTJFvkWUh2r21rMILYFlldwoABLpKXe0gn7ES2CgiiOYiVvymwex6QK9K/3VVx+mZEy2Rc+AgQw7lwYDfqhQjl2iuCba87KPgmBRl40q58qYxTEjGx+y/C+KM3Fc3RLNwXx5Wa64sqv7sYQq1oaNnvmFz1f1CciWfGjmORQJItSx76/RZ1Zfc55mMpF83AhLm3x479ry2uXGC8uUgE4iwElztO/jkx/rxoofXEHaXU5Bna31u+yUnHiYoSIs0aG+cp0am9WmwnmeICdgU2U3YETQUPOypKeTo02ccXe8K1Jfp1YgElFQ0Fvw7OMGG1hqey1sto6hFg5J6L4HuxLvmbX7Jq2Felo58SqX8/lOI03YiLyjHmv9Rs68Yt2xCzocymUbDJYIFJ+9n2IR/rDBkIVYXgSImWYWjRt5+4yo="

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./travis/before_deploy.sh
  - ./travis/deploy.sh
