language: java
jdk:
- oraclejdk8
env:
  global:
    - secure: "gkHjtbgXwu/7KYy+mxKBQYtl1v9qywHOt3DzXFLLlEAkuL6S9KgURet5qZ+Q7TpqjsRI/Qnc2mh/UMUAbTPoljWV5N3hI2SBvyvjgKEGamQpKgqXndG7M2ZdVwgHXL9p3k+ZRKMNCQGRjU0fkGUtvRPAYNoBNwjZ/UQChwtW2JnTTAQjbKnS37I5Q+sOjl9BfatSJqyMSySuZZE7UKJ82AtMvvYx6Rx4+x2dXhcmxTQjTaGM8OPkrV239/LqqWGTcvnvFZLwBpm7eIiM9FqzAliiOZQwwv0yMyQJQm8pad2K04vNeURDpbqj3EeWz/ciebrhgLhDqmCiMrBWYikrEczuElCnD2/xURmkUD0MRSUir6WHNk3U4Cb+jX/lLKKKY7BWHIcAXcQsE9M8lulURaz7vntHQQpbuSJSK17e3uC3WQZ4v1VXMo9gW69/ebwMpsd6lnXXFiTuWNnojOv+++zppOUcIXbez4j6ZTCt5YV7kE5XCxoZRyAOc4JUq+kBTaEXUvmd5BLfrz6/2YDmVe5NoO6n3ftGXnFz0qlpvxCvc2+TADIv1VMVGIAeZuptZClNdkDwCw7xbTIVrbhNBywqconjN5WiSY2Tqm0yTB4s8aJsIoNE3uOVywxcpdia6f0q0rJptMMeIkxJcl4/LiHgUCC8vPqhQfSKf1Vf5M0="
    - # ^^ GPG_KEY_NAME
    - secure: "rzKdpU9/Nkin3y4THvudfzjEDnW0n2eunaAJMpv+DWxhtqtOn/WJb3iO3JUzBJXYpk0//JOFxV1dVosRTUitGrT8QggLoy0RPPQCQVS7yW9AIH+nMQbTC35kob20Ssv6OhAiU+q7xQ/n0+AA55fnxYcDBQmiZGWNL8gZB+9uZFYLzHb6i7G4H15g3j+1AnQZLFtV64bFGm5noJTTrsPSV1cG6Hs7ZnbdAccn2r+wx5lpGziBCvNlENthZpmDnI2KJ2i3m6GzXVMyihHWFKzgiFdF4+plcqX3HxScRiu0OnX5TPwEZeHRa+rtHgrIl2MkrFPOgdJwCSrDvbq9sz0X/+Q4wQK0M5ePs3EIpZ74PuUFL2luHh6/6IegkWmRpL6hRykb8aQ99yVPzDQhANGwGXVo4+IivFhZigWYTvZYXQlfgj632jZ4GMBhKiW8nwipxRyjWmI4eYZjMGN0jcmJn0l9pLWfMs+jru58irEJ0Jo8kRT4Hn9jPj9GbRixVljQHWu0I5Ix6tAxCJHQO4MqXpaVle2WTnqZGJvgNgwyoApCQEd3TsgL8Uj+KQla+VaQjBRWlopce8D4jwvftF1+WjjLljS+rZb+iYqo8YWJOgxz5MlbR5nPJiX2FlGZ1ThsSxkFqyTAA+sNALZnDIF8lwxQgZrpkLiYy0GAf8qffeU="
    - # ^^ GPG_PASSPHRASE

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./travis/before_deploy.sh
  - ./travis/deploy.sh
