language: java
jdk:
- oraclejdk8
env:
  global:
    - secure: "HWCT+HDp4pcFfcFd03wkC16Qdu1RZu8nVcdeuH4b+jUQ3DcIYPaLtgyfVmyb6F0fprH6zcPAU/bbg6YCX5j9Dbve+tpFR5gijy2jCFLk3Hn6EnITKvpqUZ3IJTGIjmIT4+th9L1PE7JPbYXfIeJMAIZmntGmEOHHIq97u425TRfhtNag0K8V14xay83zSBx4dy21aIObewGoWYmQeIWVeroSBV+p2OHNHJuTxuMHxFtE4TgH85P4fD2wyxKT2CfHHNOosrrdSfs4DikUZCJhAZE67yFdGyRoD98e9dMiMkdqhNyTT49DtMSB4j4JOIU3s0GGixrgY4gHAQFjh/dfylVe5+x4qI0YhTpKpvErmCp9RQesfryfVNj/OGEsl23MPcrF+yEZW5TPN7POtDWneKYC0gQcjNo/9P0+Z6bdJFRHPKUzu012ua723yaR7jWjHVsn+oacmK8GwIyKRUBV5QhXA2NWIYocoBXNMQI5njKdZe2hyTVir2cMymD+oIy/Ev5jb3EsO/OQ6fNwwY2oqlilEWL7PzRtNzZYHZalU/sRwVvBXCvEEBXO7dWhoOE1ZZpKDddw2Bv8j+6yVKKH1vs9n0JQxRaufEjduTS9uDc4fG1soolY3hZE+q2aCegQmsBGygFl0mK1nH82VsyscNJ0PCI05nHkFtpJziL2ngI="
    - # ^^ GPG_KEY_NAME
    - secure: "ORn+tGwjUyXq7bPyin0e35YN2quB61mtJ7z4o3Xgrxz4NxPom9DKb/v2eTHT/XZ6Mw0ZWliIDlnbULV7z7RsE0pWB9VRbMytn0kUHNEK3yzeUMIMU6u9cBURGZmOac4+r27p2Ps/LAlVl25kaUX7V3xS01rRLwLm9iluBTcooaOfW9hwzeYA8vqCkIZ0aPr52ogn+0Y/Q1kj0MxHpbhKi9rME1J3YNr7HW1WfkVxmroyLoYfJTXaYU8fNXO2Gr6lwQ4cE61qGI57bVk9U3wZxRrmGXGjIF50BqdloXgiXXFZfdXgC1nZ6GRNmuWkFYY50bS0gb3AvokRrAVJkmyNyVj0gDmriwqAR5ZLMjMC55jNwVMEgYyaRPeCa7zhkfXkblNGxCNF4+RHVn4I0zvqH/JrukVN4cwf5/ByZ7KIMFg9s6peeGuGa+4wNkuG6JdCrue9nnCCT1AHeKJmBtljMtm/cw1PLhdO7Rw30fLEYj2qDic4pRfs+oxMOOH2Mx0JEpxEDJmYrMkeJ9mkiRgBuMa1TEGIYdiFY4weCgrlu2FPfn7Uw6Qxi0WUndCEIvZI3mYF8fCbSCkrE8Yej9NPLYcX69OKzESkiV6VZO/ThyxKMVXgyXzyaI+k4CM6Wz61a9X/Jjab1bOgD1hKlLD4WAHa4JwZWuLxRsuiHxuAiHA="
    - # ^^ GPG_PASSPHRASE

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./travis/before_deploy.sh
  - ./travis/deploy.sh
