language: java
jdk:
- oraclejdk8
env:
  global:
    - secure: "gkHjtbgXwu/7KYy+mxKBQYtl1v9qywHOt3DzXFLLlEAkuL6S9KgURet5qZ+Q7TpqjsRI/Qnc2mh/UMUAbTPoljWV5N3hI2SBvyvjgKEGamQpKgqXndG7M2ZdVwgHXL9p3k+ZRKMNCQGRjU0fkGUtvRPAYNoBNwjZ/UQChwtW2JnTTAQjbKnS37I5Q+sOjl9BfatSJqyMSySuZZE7UKJ82AtMvvYx6Rx4+x2dXhcmxTQjTaGM8OPkrV239/LqqWGTcvnvFZLwBpm7eIiM9FqzAliiOZQwwv0yMyQJQm8pad2K04vNeURDpbqj3EeWz/ciebrhgLhDqmCiMrBWYikrEczuElCnD2/xURmkUD0MRSUir6WHNk3U4Cb+jX/lLKKKY7BWHIcAXcQsE9M8lulURaz7vntHQQpbuSJSK17e3uC3WQZ4v1VXMo9gW69/ebwMpsd6lnXXFiTuWNnojOv+++zppOUcIXbez4j6ZTCt5YV7kE5XCxoZRyAOc4JUq+kBTaEXUvmd5BLfrz6/2YDmVe5NoO6n3ftGXnFz0qlpvxCvc2+TADIv1VMVGIAeZuptZClNdkDwCw7xbTIVrbhNBywqconjN5WiSY2Tqm0yTB4s8aJsIoNE3uOVywxcpdia6f0q0rJptMMeIkxJcl4/LiHgUCC8vPqhQfSKf1Vf5M0="
    - # ^^ GPG_KEY_NAME
    - secure: "QcYOedubnfwk+D47DtOWmUm8R+hIsF5+KXmZ95aC6RkgwL70Ofz8ZoLpKyFsH813dLE1xHTsWPvkCbXH4aMU6X5EzpR9oN8AOZ0Jhe0D3e97DBxMGgLXqqg/k7WJovxo68dTQNKlsMz5wDpL2u4UC1oaJ9Q3FzQ/TnRfdnZDjv0+d1YIbRCKNLV1gSSZn+6eSlu+DIJxaD3OxrBj25fk6dF5XGq3U/7fJ7t1S9xUkvS1nC3AFhrR9897OhvN/1fySin4G6hDl4m65bGOaumjuLRsNv/8WlKMoPHgcPH1bw/c+CEPFr9RRyFfBxpQ3cD1TBtDg5GmMXdmHbNsAwz38dtIqWTraFAwFWXHh8pztVYUNs8KFy+OuzIuBSSTPWq6zcSqy6fVMwkRP9BIQk/nMQ8aRZ5OCyMPjIG4GYcCgS7H5mG4sNAkEnMycUPSaSUa9pErfL3b4CSKbO2zzaw3wJKiW0VHC6Ko3JTXFW2jTzIYtCg/Kin3pTnLRjK+2VvBn2YlDDME1mypeCDGrDZCWD4tGWrVucCbF8JAX4g+CFdogkVNvZ7OTKXsiSyTnCCaXpqtHYiWhkMnD/aWEsRQKFVGPIOucPoWlNdRVKEOrsc0/KbjbS4/B6WfHrdxL2sB3G1vp5RIH5Xt4sErQj+H1xLKtmXYGQDqQ+pA0Cspk5c="
    - # ^^ GPG_PASSPHRASE

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./travis/before_deploy.sh
  - ./travis/deploy.sh
